
default: &default
  adapter: postgresql
  pool: 5
  encoding: utf8

development:
  <<: *default
  database: recruitapp_development
  pool: 5
  username: postgres
  password: password

test:
  <<: *default
  database: recruitapp_test
  pool: 5
  username: postgres
  password: password

production:
  <<: *default
  database: recruitapp_production
  pool: 5
  username: postgres
  password: password
